apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nq112u85m-dotnet-basic
  janus-idp.io/tekton: nq112u85m-dotnet-basic
  backstage.io/kubernetes-id: nq112u85m-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nq112u85m-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
